#!/usr/bin/lua
local site = require 'gluon.site_config'
local uci = require('simple-uci').cursor()
local unistd = require 'posix.unistd'
local location = uci:get_first("gluon-node-info", "location")

if not unistd.access('/lib/gluon/domains/') then
    uci:set("gluon-node-info", location, "ffue_site", site.site_code)
    uci:commit('gluon-node-info')
else
    local domain = uci:set("gluon-node-info", location, "ffue_site")
    if domain and not unistd.access('/lib/gluon/domains/' .. domain .. '.json') then
        io.stderr:write(string.format("Warning: invalid mesh domain '%s' configured, resetting to default...\n", domain))
    else
        uci:set('gluon', 'core', 'domain', domain)
        uci:commit('gluon')
    end
end

